name: docker-example

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest

    steps:

    # Checks out the repo with full history
    - uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          submodules: 'recursive'
          persist-credentials: false

    - name: Build docker image
      run: |
        docker build . -t docker-example --no-cache --pull

    - name: Run docker image
      run: |
        docker run -v `pwd`:/home/user/repo docker-example bash --login -c "ls ~/repo"